/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Food` | `/Food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Header` | `/Header`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Snake` | `/Snake`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SnakeGame` | `/SnakeGame`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logIn-page` | `/logIn-page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/main` | `/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signIn-page` | `/signIn-page`; params?: Router.UnknownInputParams; } | { pathname: `/types/types`; params?: Router.UnknownInputParams; } | { pathname: `/utils/checkEatsFood`; params?: Router.UnknownInputParams; } | { pathname: `/utils/checkGameOver`; params?: Router.UnknownInputParams; } | { pathname: `/utils/randomFoodPosition`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Food` | `/Food`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Header` | `/Header`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Snake` | `/Snake`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SnakeGame` | `/SnakeGame`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/logIn-page` | `/logIn-page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/main` | `/main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/signIn-page` | `/signIn-page`; params?: Router.UnknownOutputParams; } | { pathname: `/types/types`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/checkEatsFood`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/checkGameOver`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/randomFoodPosition`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Food${`?${string}` | `#${string}` | ''}` | `/Food${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Header${`?${string}` | `#${string}` | ''}` | `/Header${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Snake${`?${string}` | `#${string}` | ''}` | `/Snake${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SnakeGame${`?${string}` | `#${string}` | ''}` | `/SnakeGame${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/logIn-page${`?${string}` | `#${string}` | ''}` | `/logIn-page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/main${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/signIn-page${`?${string}` | `#${string}` | ''}` | `/signIn-page${`?${string}` | `#${string}` | ''}` | `/types/types${`?${string}` | `#${string}` | ''}` | `/utils/checkEatsFood${`?${string}` | `#${string}` | ''}` | `/utils/checkGameOver${`?${string}` | `#${string}` | ''}` | `/utils/randomFoodPosition${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Food` | `/Food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Header` | `/Header`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Snake` | `/Snake`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SnakeGame` | `/SnakeGame`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/logIn-page` | `/logIn-page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/main` | `/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/signIn-page` | `/signIn-page`; params?: Router.UnknownInputParams; } | { pathname: `/types/types`; params?: Router.UnknownInputParams; } | { pathname: `/utils/checkEatsFood`; params?: Router.UnknownInputParams; } | { pathname: `/utils/checkGameOver`; params?: Router.UnknownInputParams; } | { pathname: `/utils/randomFoodPosition`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
